version: "3.2"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
      - redis
    networks:
      - common_network
  postgresdb:
    image: 'postgres:15.2-alpine'
    container_name: postgresdb
    environment:
      - 'POSTGRES_DB=harbor'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - common_network
  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: 'redis'
    ports:
      - "6379:6379"
    command: 'redis-server'
    networks:
      - common_network
networks:
  common_network:
    driver: bridge
volumes:
  db:
    driver: local